server:
  port: 8080
spring:
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/advogado-freelancer
    password: postgres
    username: postgres
    driverClassName: org.postgresql.Driver

